### ISSUE TITLE
Przeniesienie sources i indexers z ptw do fanfilm

### ISSUE THREAD

**Issue by xulek** [CherryKodi/cherry-dev#2]
Jak w temacie, trzeba przenieść te dwa foldery do wtyczki fanfilm, bo ona jako jedyna z nich korzysta. O ile to możliwe do zrealizowania w prosty sposób :)

[https://github.com/CherryKodi/cherry-dev/tree/master/script.module.ptw/lib/resources/lib/indexers](url)
[https://github.com/CherryKodi/cherry-dev/tree/master/script.module.ptw/lib/resources/lib/sources](url)

**Comment by rysson** [comment]
I nie widać sensu używania ich w innych potencjalnych wtyczkach?
Jeśli tak, to zajrzę tam wieczorem mam nadzieję.

**Comment by xulek** [comment]
Nie, są to pliki pisane tylko pod tą wtyczkę i zastosowanie ich w innych byłoby raczej ciężkie

**Comment by notoco** [comment]
Próbowałem - ale mnie to przerasta :) - starałem się wrzucić je spowrotem do plugin.video.fanfilm - ale w kółko wybija błąd że nie może znaleźć modułu...

**Comment by xulek** [comment]
Ja nie za dobrze ogarniam struktury plików pythona, więc nie wiem czy da się to zrobić zwyczajnie zmieniając foldery. Ale jeśli się nie da to można to zrealizować przez zmianę folderu z resources na jakiś inny, tylko trzeba będzie później zamienić ścieżki w importach plików. Bo resources jest już importowany z script.module.ptw więc nie wiem czy drugi folder o takiej samej nazwie ale z innymi plikami (sources, indexes) można zaimportować z innego miejsca.

**Comment by notoco** [comment]
Próbowałem - nie za bardzo to szło - drugi folder o tej samej nazwie odpadał, próbowałem inną nazwę folderu i zmieniać ścieżki - ale też nie szło...

**Comment by rysson** [comment]
Koledzy, spokojnie, dajcie się pobawić :-)

Zacznę od tego, że plugin.video.fanfilm.lite ma w zależnościach:
* script.fanfilm.media
* script.fanfilm.lite.metadata
których nie ma w ffl-dev. 

A za to nie ma w zależnościach ptw, chyba, że pośrednio, zaraz sprawdzę w zip-ach.

**Comment by rysson** [comment]
~~Zagubiłem się, gdzie jest skrypt „ptw”?~~
**EDIT** Nie było pytania, jest w dev tutaj!

**Comment by xulek** [comment]
Tak, rób na tym repozytorium i z tego FanFilmu

**Comment by rysson** [comment]
Jasne. Powiedz mi jak to działa(ło), że część kodu jest w PTW (właśnie mamy zabrać) a w ffl nie ma PTW w zależnościach? Ffl używa tego kodu z PTW czy nie?

**Comment by rysson** [comment]
@xulek, drugie pytanie, przecież w plugin.video.fanfilm.lite są już te katalogi (tzn. indexers i sources). 
**EDIT:** Mało tego, wersje w obu dodatkach wyglądają na bliską kopię, tzn. różnią się końcem linii (ktoś lubi windowsa!), odwołaniem „lite” i proxy. Może 10 linijek jest różnych.

**Comment by notoco** [comment]
Rysson. Rób na tym repozytorium. Obie te wersje gdzieś od miesiąca są bardzo bliskie, pierwotne różnice się zatarły  i dążymy do jednej wersji, opartej na tym kodzie który jest tutaj, oczyścimy go tylko z super favorites, zostawimy jako opcję w menu parowanie. Ale razem z xulkiem stwierdziliśmy że żeby to miało ręce i nogi trzeba posprzątać w kodzie. Jak go uporządkujemy zrobi się szybki "rebranding" i fanfilm będzie miał id fanfilm lite ale nazwę wtyczki fanfilm - większość użytkowników używa fanfilm lite, duży fanfilm miał zastosowanie w buildach, ale stwierdziliśmy z xulkiem że dubluje się robota. Repo dev będzie tutaj.
Xulek wydzielił wraz z powstaniem tego repo moduł ptw, ja jeszcze tego nie wrzuciłem do siebie... I raczej już nie wrzucę... Bo to jednak tu będzie główna akcja developerska...  A repo dev u mnie będzie zamknięte. Zostanie tylko repo z gotowymi zipami dla kodi.
W ffl są te katalogi, ale jest też ogólny katalog z innymi rzeczami z których korzystają inne wtyczki i xulek wydzielił to do script.module.ptw. Ale wydzielone zostały też te dwa katalogi które jednak winny być stricte w fanfilm

**Comment by rysson** [comment]
Aaaa, *Przeniesienie sources i indexers z ptw do **fanfilm***. A nie do fanfilm.lite. 
Widzisz zmyliło mnie :)

**Comment by notoco** [comment]
Olej fanfilm lite. On powstaje przez skrypt bash z dużego fanfilm. Kasował dwie zależności i zmieniał id. Fanfilm lite zmieni się po sprzątnięciu kodu w fanfilm.
Co do fanfilm.media - tam są tylko ikonki. W fanfilm(lite).metadata jest baza wykorzystywana przy wyszukiwaniu filmów. Rozdzieliliśmy to na samym początku żeby można było mieć 2 niezależne wersje ff.
Mam nadzieję że rozumiesz to do czego dążymy. Pracujemy na kodzie ff. Jak go usprzatniemy zrobimy rebranding na ff lite co by użytkowników nie wprowadzać w konsternację, ale zmienimy nazwę na ff.

**Comment by notoco** [comment]
I już ffl-dev zarchiwizowany co by nie mieszać.

**Comment by rysson** [comment]
@notoco, wydaje mi się, że widzę światełko w tunelu :)
@xulek , czy mi się wydaje, czy jeszcze PTW nie jest produkcyjne puszczony. Nie widzę go w zipach w CHERRY.
Pytam, bo mam błędu importowania (zanim przesuwałem katalogi) i patrzę, czy czegoś nie zepsułem na wejsciu.

**Comment by xulek** [comment]
nie był puszczony w repo cherry publicznie, to jest świeży pomysł i realizacja dostępna tylko na cherry-dev jak na razie

**Comment by rysson** [comment]
@xulek, to dobrze, ale najważniejsze, czy Wam działa cherry-dev w obecnej postaci?
Cokolwiek co używa ptw?

**Comment by rysson** [comment]
Swoją drogą wnętrze PTW można wrzucić w katalog „ptw”, wtedy nie powinno być kolizji nazw. Można też usunąć resources/lib. Zostanie lib/ptw/...
Mogę zacząć to robić, ale nie chciałbym popsuć czegoś co działa.

**Comment by xulek** [comment]
zanim wrzucałem to sprawdzałem i działało to dobrze, a jest jakiś problem? Twój sposób spowoduje zmianę w każdej wtyczce w repo cherry-dev bo wszędzie jest import po resources z ptw :/

Edit. No ale ewentualnie można sie pokusić o takie rozwiązanie, tylko trzeba będzie zmieniać wszystkie importy

**Comment by rysson** [comment]
Tak, spowoduje, dlatego pytam zanim zacznę zmieniać. Mam błędy importowania:
```python
21:33:33.430 T:139824447080192   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named resources.lib.libraries
                                            Traceback (most recent call last):
                                              File "/home/robson/.kodi/addons/plugin.video.fanfilm/service.py", line 19, in <module>
                                                from resources.lib.libraries import log_utils
                                            ImportError: No module named resources.lib.libraries
```

Ponieważ ręcznie dodawałem modułu (od razu linki do repo) mogłem coś skopać.
Jak u Ciebie działało, jest szansa, że będzie działać.

Choć wolę sprawdzić, może inny,zewnętrzny plugin korzystał ze ścieżki „resources.lib”, to by wyjaśniało problem.

**Comment by rysson** [comment]
Pytanie do kodu. Czemu niemal w każdej akcji mamy:
```python
from resources.lib.indexers import navigator
```
I to samo z movies itd.

Czy to oszczędność czasu, żeby nie ładować modułu jak akcja go nie dotyczy? 
Trochę to dziwne.

**Comment by xulek** [comment]
sprawdź czy w plugin.video.fanfilm nie masz przypadkiem w resources _init_.py albo folderu plugin.video.fanfilm/resources/lib, jeśli jest to go wywal.

**Comment by xulek** [comment]
`from resources.lib.indexers import navigator`

Odnośnie tego, to już było zrobione wcześniej w pluginie incusrion, na którym bazuje fanfilm. Można próbować ładować moduł w miejscu, w którym jest potrzebny ale czy chcemy sobie utrudniać życie? Nie powoduje to jakiś szczególnych strat na wydajności

**Comment by rysson** [comment]
Moja wina, podlinkowałem PWT, ale nie było go w bazie `.kodi/userdata/Database/Addons27.db`
Po instalacji z zip działa. Przepraszam za zamieszanie.

Co prawda dalej będę proponował zmianę nazwy katalogu, ale może najpierw się wykażę zmianą z tego issue.

Na 90% macie rację, problemem jest ta sama ścieżka. Zaraz to zweryfikuję.

**Comment by rysson** [comment]
> Można próbować ładować moduł w miejscu, w którym jest potrzebny

Ale on właśnie jest kilkadziesiąt razy w miejscu użycia w default.py zamiast raz na górze.
Zapewne z powodu wydajności. Zostawmy to na razie.

**Comment by rysson** [comment]
Mogę jeszcze zapytać o powód tego przenoszenia? Czy przeszkadza bardzo, że tylko FanFilm korzysta?

Bo to są nie tylko katalogi. Trzeba libriaries podzielić a to już większa robota. Inaczej przestaną działać takie rzeczy jak
```python
from resources.lib.sources import sources
```
Albo `lib/resources/lib/libraries/libtools.py:176`:
```python
from resources.lib.indexers import movies
```

Dzisiaj muszę kończyć. Jak wolicie rozdział, to zobaczę jutro jak to pociąć.

**Comment by xulek** [comment]
jedyny powód to to, że korzysta z niego tylko fanfilm. Więc wizualnie lepiej by to wyglądało jakby znajdowało się w fanfilmie. Jeśli chodzi o samo działanie to nie ma to najmniejszej różnicy czy jest tu czy tam :P

**Comment by rysson** [comment]
To na razie proponuję zostawić. Albo sprawdzić czego z PWT potrzebują pozostałe wtyczki i czy to się nie zazębia.
3V się

**Comment by xulek** [comment]
pozostałe wtyczki nie tyle co potrzebują ale powinny móc korzystać z resources/lib/libraries ponieważ jest to biblioteka pomocnicza przy pisaniu każdej z nich. Takie jest założenie

**Comment by notoco** [comment]
Jak to się mówi, nie znam się ale napisze.... A gdyby tak sources i indexers zostawić w plugin.video.fanfilm, a libraries pobierać z zewnątrz. Przy zmianie nazw katalogów w ptw nie będzie chyba tragedii żeby ogarnąć pozostałe wtyczki...

**Comment by rysson** [comment]
@xulek, pojmuję intencję, ale... :-)  (_patrz niżej_)
@notoco, zmiana nazw katalogów (czyli nazw modułów), szczególnie, że to jeszcze nie ujrzało światła dziennego, nie stanowi problemu, ale ... :-)  (_patrz niżej_)

Problemem jest konstrukcja. Napiszę jak to wygląda po wczorajszym bardzo krótkim przyglądaniu się.
Jest biblioteka, którą widzę też we wtyczkach MrKnow, która robi wiele z czarnej roboty. Tą są wszystkie trzy katalogi. Jakaś część z libraries (np. parseDOM¹) jest też ogólnego zastosowania i z tej części korzystają nasze (jeśli mogę tak napisać) wtyczki.
Niemniej wszystkie trzy katalogi stanowią całość (sięgają do siebie nawzajem). Jeśli chcemy to rozdzielać, to ja proponuję chwilowe PTW przenieść w całości do FanFilm a następnie wyjąć tylko to co jest ogólne i niezbędne do nowej wtyczki PTW (scripts.module.ptw) i umieścić w nowym katalogu „ptw”. A w starym kodzie (czyli przeniesionym do FanFilm) zrobić odwołania do ptw, żeby nie dublować kodu. Oczywiście we wszystkich wtyczkach też zmienić odwołanie (do nowego ptw).

Jeśli to brzmi sensownie, to mogę się tym zająć np. jutro. Dzisiaj nie mogę. Swoją drogą jestem w robocie i czas się robotą zająć. 
Miłego dnia.


¹) BTW. Od dwóch dni przerabiam tę funkcję, będzie miała sporo większe możliwości. Mam nadzieję, że poprawi się czytelność kodu czyli łatwość parsowania HTML we wtyczkach przy okazji. Przynajmniej nowych, bo trzymam kompatybilność, więc nie ma przymusu zmiany obecnego kodu. Później pokażę przykłady.

**Comment by notoco** [comment]
Dla mnie to brzmi sensownie i chyba o to chodzi - w sumie to opisałeś to, co ja próbuję tłumaczyć właściwymi słowami :) - jak już mówiłem programistą nie jestem.

**Comment by xulek** [comment]
Jasne jeśli tylko Ci się chce to próbuj, jestem ciekaw jak to ostatecznie będzie wyglądać :)

**Comment by rysson** [comment]
Prace w toku, wrzuciłem do osobnej gałęzi na razie. Rozdzieliłem i naprawiłem błędy importowania, ale reszta nie działa (wszystkie listy są puste, czy to w FanFilm czy w pozostałych wtyczkach). Tyle jest miejsc gdzie *expect* łyka wszystko, że przez to nie ma żadnej informacji gdzie poległo.
W wolnej chwili przerobię to na tyle, żeby znaleźć błędy.

**Comment by rysson** [comment]
Pewien nieśmiały sukces zgłaszam. Jeden brakujący `import gzip` i parę dni śledzenia, niech to...
Ale nie ma tego złego, co by na dobre nie wyszło. Pojawił się zalążek `ptw.debug`,  w którym będę dodawał kolejne narzędzia. Na razie jest:
* `log_exception()` – warto używać niemal przy każdym `except` (takim, w którym nie jest to spodziewane)
* `start_trace()` – włącza logowanie *każdego* wywołania wraz z argumentami (perdylion logów)

Wygląda, że teraz z grubsza działa. Jutro posprzątam, dam Wam do oceny i zrobię merge.

**Comment by rysson** [comment]
Przykład logów:
```
22:01:56.832 T:140232200537856   DEBUG: [Bajki online][STACK]               $HOME/.kodi/addons/plugin.video.BajkiOnline/main.py:133:
                                                                            ListowanieBajek(url='http://bajkionline.com/', r=u'?????', result=u'?????')
22:01:56.833 T:140232200537856   DEBUG: [Bajki online][STACK]                     $HOME/.kodi/addons/script.module.ptw/lib/ptw/libraries/client.py:35:
                                                                                  request(url='http://bajkionline.com/', close=True, redirect=True, error=False, proxy=None, post=None, headers=None, mobile=False, XHR=False, limit=None, referer=None, cookie=None, compression=True, output='', timeout='30', handlers=u'?????', opener=u'?????', cookies=u'?????', ssl=u'?????', ssl_context=u'?????', _headers=u'?????', NoRedirectHandler=u'?????', request=<function request at 0x7f8a12530668>, response=u'?????', s=u'?????', cf=u'?????', authUrl=u'?????', makeAuth=u'?????', result=u'?????', kuki=u'?????', i=u'?????', content=u'?????', encoding=u'?????', su=u'?????', netloc=u'?????', ua=u'?????', item=u'?????', response_headers=u'?????', response_code=u'?????', e=u'?????')
```

**Comment by rysson** [comment]
Niestety z braku czasu nie miałem jak porobić porządków (szczególnie unit-testów). Wystawiłem Pull-Request  #9, tam można obejrzeć zmiany. Tamten kod należy przetestować o co Was proszę.

**Comment by rysson** [comment]
Zatwierdzone i wrzucone do mastera przez @xulek – dzięki!
Testy dopiszę na dniach (oby!) i będę wrzucał od razu do mastera, bo to nie koliduje z kodi.
