### ISSUE TITLE
git

### ISSUE THREAD

**Issue by rysson** [CherryKodi/cherry-dev#32]
@xulek, eee, coś Ty zrobił z repo? Czemu mam tylko 2 commity, z czego pierwszy „inital commit”?
Nie pchnąłeś czegoś przypadkiem jako `git push --force`?

**Comment by xulek** [comment]
Była mała awaria przy commitcie (nie drążmy haha), wyresetowałem historię specjalnie :P

**Comment by rysson** [comment]
OK, nie drążę. A może przywrócimy ciągłość do momentu wtopy? I potem cherry-pink to co po wtopie?

**Comment by xulek** [comment]
Nie wiem czy to możliwe bo to jest nowy branch przeniesiony do master a master usunięty i nie wiem czy jest sens. Na ten moment wszystko działa tak jak ma działać więc może to być nowy punkt wyjścia według mnie.

**Comment by rysson** [comment]
No poza tymi, którzy mają pobrane do siebie. A jak mają jakieś zmiany, to mają problem.
Na szczęście ja mam tylko jedną gałąź odszczepioną przed wpadką, więc jakoś ją złożę, choć nie napawa mnie to radością.

**Comment by rysson** [comment]
Zastanawiam się czy nie lepiej usunąć całego repo i nie założyć jeszcze raz. W starym były wpadki binarne, tzn. całe ZIP-y były wrzucone, przez co repo trochę waży (~60M), a historii już nie ma.
Sam nie wiem...

**Comment by xulek** [comment]
A dlaczego nie zostawić tego tak jak jest? Po co sobie życie komplikować? To nie jest żadne rocket science, że historia jest nam bardzo potrzebna :P Ale z drugiej strony trochę Cię rozumiem bo widzę, że starasz się być w tym co robisz perfekcjonistą. Wnioskuję tak po czystym kodzie i super dokumentacji do niego

**Comment by rysson** [comment]
No teraz jest tak połowicznie. Commity są w repo ale nie w historii. Sama historia też się czasem przydaje. Głównie chodzi o jej brak w porównaniu do lokalnych repo i gałęzi. Byłoby zabawnie, jakbym po prostu próbował megować.

Ale się nie upieram, niech zostanie tak jak jest,
