### ISSUE TITLE
plugin.video.shinden nie dziala

### ISSUE THREAD

**Issue by po50on** [CherryKodi/cherry-dev#38]
plugin.video.shinden nie dziala

**Comment by xulek** [comment]
w czym problem? u mnie działa

**Comment by po50on** [comment]
umnie tylko dziala ranking i tylko znajduje 1 link
to sie dzieje taksamo na pc i  androidzie

**Comment by xulek** [comment]
[plugin.video.shinden-2019.01.26.0.zip](https://github.com/CherryKodi/cherry-dev/files/2848693/plugin.video.shinden-2019.01.26.0.zip)

Spróbuj tego

**Comment by po50on** [comment]
ten dziala dobrze
