### ISSUE TITLE
Scrapper cda.pl

### ISSUE THREAD

**Issue by notoco** [CherryKodi/cherry-dev#5]
Skoro nie jestem w stanie pomóc przy "sprzątaniu", "czyszczeniu" to podrzucę pomysł na przyszłość, po porządkach.
Na cda.pl jest sporo filmów, wiele z nich ostatnio jest z dźwiękiem 5.1 - czego ewidentnie brakuje w serwisach PL - ja tam wolę 720p ale w 5.1 niż 1080p w stereo. Wiele osób tego i tak nie wychwyci, ale część ma podłączone boxy do amp....
Problemem są nazwy na cda - w postaci "S4m0loty dwa" - zamiast "Samoloty 2" - owszem zdarzają się wyjątki, gdzie tytuły odpowiadają: https://www.cda.pl/video/230861745?wersja=1080p - "Samoloty 2" (i polecam - sceny z przelotem przez pożar w 5.1 to sama przyjemność)
Wielu tych filmów nie da się wychwycić - ale te które się da, warto by było wychwytywać...
Ale... ale wtyczka phantom ma funkcję kojarzenia filmów z filmweb - korzysta z zewnętrznej bazy gdzie powiązana jest nazwa oryginalna pobierana z filmweb z (chyba) identyfikatorem filmu na cda.... może tu możnaby uderzyć? Oczywiście trzeba by to zrobić oficjalnie...

**Comment by notoco** [comment]
Rozwiązanie tymczasowe to dodawanie linków do tych filmów do innych serwisów które już są obsługiwane - ale jak wiadomo wymagają logowania ;( 
Tu się prosi coś takiego jak kiedyś było - filmkodi... czyli że sami możemy dodawać sobie linki do jakiegoś pliku wraz z tytułem/id :)

**Comment by rysson** [comment]
@notoco, możesz nieco rozwinąć temat? W filmodi było ręczne dodawanie linków? I czy piszemy o FanFilm?
Ja jeszcze nie zaglądałem tam i nie wiem np. skąd jest ta baza danych, w sensie kto tym zarządza i czym karmi.

**Comment by xulek** [comment]
Dodany scrapper cda

commit https://github.com/CherryKodi/cherry-dev/commit/7785aa269be49f31445ce931f0ce0f65dd5859e1
