### ISSUE TITLE
Fanfilm - udostępnienie dla mas

### ISSUE THREAD

**Issue by notoco** [CherryKodi/cherry-dev#54]
Jak wiadomo - wszyscy jesteśmy głodni aktualizacji FanFilm. Z różnych powodów i racji, pojawił się pomysł żeby utworzyć odrębne repozytorium na kodiwpigulce. Repozytorium zawierające tylko zipy fanfilmu i jego zależności.
Pojawił się problem z wersjami fanfilm udostępnionymi jakiś czas temu dla członków VIP grupy PolishTeamWizards. Wersje te są oznaczone klasycznie - czyli plugin.video.fanfilm-YYYY.MM.DD - co powoduje problem z wersjami w kwp - zastosowanie dzisiejszej daty 2019.03.13 nadpisało by użytkownikom VIP ich wersje. Owszem mogą nie instalować repo kwp, to raczej świadomi użtkownicy, i tu byłby problem rozwiązany. Próbowałem testowo robić repo z nazwą np 2019.03.13 i v2019.03.13 i x2019.03.19 - jednak zawsze wersja bez literki nadpisuje...
Drugim rozwiązaniem jest zmiana nazwy... już kiedyś o tym rozmawialiśmy chyba. Padła propozycja fanfilm.reborn - czyli odrodzenie... 
Nazwa dobra - bo skoro prace jakoś idą, i jest zapał - to będzie działać. Użytkownikom nic nie namiesza. Nowym użytkownikom da się nad tym przejść.
Co wy na to?
Jakieś propozycje? Owszem - najłatwiej by było wrzucić w repo cherry poprawioną wersję (dalej pozostaje problem z wersjami VIP) - ale tu też są pewne ograniczenia. @CherryKodi  - może jesteśmy w stanie je przeskoczyć?

**Comment by kodiwpigulce** [comment]
Ja jestem za lekko zmianą nazwy i wrzuceniem do repo kwp lub utworzenie odrębnego repo tylko pod FF. 
Można repo hostować u nas na serwerze, mamy kilka domen.

**Comment by notoco** [comment]
No to jest nas dwóch za zmianą nazwy.

**Comment by kodiwpigulce** [comment]
Tylko czy zmiana nazwy też nie wprowadzi niepotrzebnego chaosu.

**Comment by notoco** [comment]
Dokładnie. Już to przerabialiśmy z FanFilm Lite...
Musi być jakaś metoda z tymi nazwami... Coś co pozwoli na nienadpisywanie wersji Vip.

**Comment by notoco** [comment]
A jednak - robię próby z różnymi numeracjami.
i tak. plugi z id wersji 1.0.0N - aktualizuje się do 1.0.2 jak zawsze.
Ale jeśli jest plugin oznaczony jako V1.0.N - to on jest uznawany za najnowszy a nie zaś 1.0.2
Czyli możnaby zrobić tak, że wersjaz repo cherry vip miałaby oznaczenie plugin.video.fanfilm-V2019.03.13, i nawet jeśli wyjdzie wersja plugin.video.fanfilm-2019.04.20 - to i tak wersją "najbardziej aktualną w tym przypadku będzie wersja z repo cherry vip.
Nie musimy zmieniać nazwy!
![screenshot000](https://user-images.githubusercontent.com/36659110/54294272-9aca7c00-45b1-11e9-8fca-0dfbbf5f8b0f.png)

**Comment by rysson** [comment]
Wystarczy do wiki zajrzeć: https://kodi.wiki/view/Addon.xml#version_attribute

```
How versioning works
2.2.9 is newer than 2.2.1
2.2.10 is newer than 2.2.1
2.3.0 is newer than 2.2.9
2.2.1 is newer than 2.2.1~alpha
2.2.1 is newer than 2.2.1~beta
2.2.1~beta is newer than 2.2.1~alpha
2.2.1~beta3 is newer than 2.2.1~beta2
2.2.1~beta10 is newer than 2.2.1~beta1
```

**EDIT**: A jeszcze dokładniej jest w źródłach: https://github.com/xbmc/xbmc/blob/master/xbmc/addons/AddonVersion.cpp, 
funkcja `AddonVersion::CompareComponent`

**EDIT2**: 
```c++
      if (*a && *b && (!isdigit(*a) || !isdigit(*b)))
      {
        if (*a == '~') return -1;
        if (*b == '~') return 1;
        return isdigit(*a) ? -1 : 1;
      }
```
Tutaj widać, pomijając tyldy, cyfry są zawsze przed innymi znakami.

**Comment by notoco** [comment]
To wiem. Ale mi chodzi o to żeby w niektórych wypadkach wersja starsza nie była nadpisana przez nowszą. Problem jest z repo ptw VIP. Zamkniętym, ale troszkę osób z tego korzysta. I doświadczalnie wyszło że v2019.01.27 jest nowsze niż 2019.03.13. czyli wersja VIP (oznaczona v na początku) nie będzie nadpisana przez fanfilm. Dla zwyklego usera i dla nas już nie ma to żadnego znaczenia... Gdyż repo VIP ma już zmieniona nazwę na v2019.x.x.
Także my pozostajemy przy klasycznej nazwie i numeracji która już została przyjęta yyyy.mm.dd.
U nas się nic nie zmienia. Pozostaje jak było, pod względem nazwy jak i numeracji.

**Comment by rysson** [comment]
@notoco, no dokładnie. Ja tylko podałem źródło tego co zaobserwowałeś doświadczalnie.
[Linia 79](https://github.com/xbmc/xbmc/blob/master/xbmc/addons/AddonVersion.cpp#L79) (czyli ostatni return z poprzedniego komentarza) własnie zwraca jako nowsze literę jeśli jest porównywana z cyfrą.
Innymi słowy, obserwacje są potwierdzone w kodzie źródłowym kodi. Tak napisałem, jakby ktoś miał wątpliwości czy zawsze zadziała.

**Comment by notoco** [comment]
Uwielbiam cię za to, że to co my robimy doświadczalnie ty wygrzebujesz w kodzie, poprawiasz i naprowadzasz.

**Comment by xxcriticxx** [comment]
@rysson chyba zrobiles bubla linia `75` czy `79`?

**Comment by rysson** [comment]
@xxcriticxx, jasne, dzięki!
Linia 75 to początek if, który łapie przypadek porównania cyfry z innym znakiem (np. literą), a linkowana linia 79 to wynik porównania (cyfra jest mniejsza czyli starsza).
Poprawiłem komentarz.

**Comment by notoco** [comment]
Więc tak, podsumowując. fanfilm powstający z tego źródła ma dalej nazwę FanFilm, bez żadnych reborn, resurection, restore, reanimation ;). Oznaczenie wersji pozostaje zgodnie z tym co od dawna jest prowadzone - czyli datą wydania. Pojawia się raz na miesiąc, chyba że nagle padną wszystkie źródła. Udostępnione zipy będą w repozytorium kodiwpigulce. Tu się zajmujemy developerką, na forum kodiwpigulce pomagamy z ogólnymi problemami - typu nie umiem kliknąć bo mi się nie chce.

**Comment by RagnarLodbrok1981** [comment]
Panowie to jaka wersja FANFILM-u jest najbardziej aktualna? i skąd ją pobrać?

**Comment by notoco** [comment]
Z repo w kodiwpigulce.pl

**Comment by RagnarLodbrok1981** [comment]
https://repo.kodiwpigulce.pl/ to jest to?

**Comment by notoco** [comment]
tak.

**Comment by RagnarLodbrok1981** [comment]
dziękuję bardzo mam pytanie gdy wolno się buforuje obraz skacze klatkami za chwilę traci się głos trzeba dać pauzę odczekać kilka minut i po pewnym czasie znów pauza

**Comment by notoco** [comment]
To nie wina Fanfilmu - tylko sieci/połączenia/serwerów.

**Comment by RagnarLodbrok1981** [comment]
rozumiem słyszałem o takich programach ezmaizantep advencer setting czy jakoś tak pewnie nazwy źle napisałem, podobno pomagają.

**Comment by RagnarLodbrok1981** [comment]
notoco czyli niema żadnych sposobów by buforowanie było szybsze?

**Comment by notoco** [comment]
Poczytaj o real debrid

**Comment by kashkash18** [comment]
Rok temu wykupiłem RD na próbę i posiadam do dziś. Jest to jedyna usłuaga za którą płace ale gra jest warta świeczki.

**Comment by RagnarLodbrok1981** [comment]
kashkash18 płacisz jednorazowo czy co miesiąc i ile zapłaciłeś jeśli można wiedzieć

**Comment by kashkash18** [comment]
Wykupuje na 180 dni za 16€. Dostajesz również punkty lojalnościowe którymi możesz wydłużyć ważność konta o kolejne 30 dni

**Comment by RagnarLodbrok1981** [comment]
oki dziękuję za info pozdrawiam

**Comment by RagnarLodbrok1981** [comment]
Szanowni kto jest twórcą wtyczki FANFILM?

**Comment by notoco** [comment]
Każdy. Nie ma jednego autora.

**Comment by RagnarLodbrok1981** [comment]
notoco więc do kogo zwracać się jak jakieś źródła nie działają lub gdy jest jakiś film czy serial w FanFilm a niema żadnego źródła lub pod serialem brak jakiegokolwiek sezonu po prostu pusto

**Comment by notoco** [comment]
Omawiane tysiące razy.... 
1. jeśli źródła nie działają - to oznacza że na stronach które obsługuje FF wygasły linki (lub nie odpowiadają z powodu przeciążenia serwerów). FanFilm nie zawiera żadnych źródeł, jedynie przeszukuje już dostępne strony - jeśli na nich nie działa - to w FF też nie.
2. jeśli nie ma źródeł - to oznacza że na stronach które obsługuje FF ich nie ma. Albo że na stronie zaszły zmiany - wtedy trzeba czekać na poprawkę scrapera.
3. Jeżeli serialu/filmu brak, brak sezonu, to oznacza że jest nieprawidłowo opisany - albo na stronach albo w tmdb. Na stronach ciężko poprawić (ale niektóre serwisy pozwalają) - w tmdb można samemu poprawiać, dodawać seriale. Wtedy FanFilm zaciągnie prawidłowe nazwy/roczniki itp i będzie mógł szukać na stronach.

**Comment by RagnarLodbrok1981** [comment]
dziękuję za wyczerpującą odpowiedź
