### ISSUE TITLE
Phantom 

### ISSUE THREAD

**Issue by xxcriticxx** [CherryKodi/cherry-dev#58]
sorry za off topic ale nie wiedzialem gdzie znajde wiecej majstrow w jednym miejscu

dziala wam Phantom 2019.03.15? ja mam taki error jak naciskam na HD filmy @notoco jakbys mogl to zglosic tam gdzie trzeba

sorry za off topic again

![Capture](https://user-images.githubusercontent.com/15007183/54681308-63dcf480-4ae2-11e9-88bf-8b675132cd30.PNG)

**Comment by notoco** [comment]
Powiem tak  - SOA - u mnie działa ;)
Błędy zgłaszaj tutaj - to jedyny kanał.
https://www.facebook.com/pages/category/Software/Phantom-KODI-1571086686537531/
Z tego co widziałem niektórzy mają ten błąd - u mnie pojawiał się na wcześniejszej wersji - na obecnej go nie mam.

**Comment by xxcriticxx** [comment]
@notoco nie posiadam konta fb jak dasz rade zglosic to bede wdzieczny

**Comment by notoco** [comment]
Jest to już zgłoszone - ale jak już mówiłem - u mnie działa (ale mam podłączone konto)

**Comment by notoco** [comment]
![obraz](https://user-images.githubusercontent.com/36659110/54736217-6145d200-4baa-11e9-8026-745a3954c604.png)
Info z dzisiaj/wczoraj

**Comment by notoco** [comment]
https://www.cda.pl/
![obraz](https://user-images.githubusercontent.com/36659110/54746890-acbda780-4bcd-11e9-9411-094246690708.png)

**Comment by xxcriticxx** [comment]
@notoco ja mam dalej 403 i jest 22.03
