### ISSUE TITLE
Alltube - problem z niektórymi tytułami...

### ISSUE THREAD

**Issue by notoco** [CherryKodi/cherry-dev#6]
Przykład - wyszukiwanie filmu - "Samoloty 2"
Link do filmu na alltube: http://alltube.pl/film/samoloty-2-planes-fire-rescue-2014/12854
Tytuł na alltube i rok odpowiadają tym na Trakt.
Przykład - wyszukiwanie filmu - "Samoloty"
Link do filmu na alltube: http://alltube.pl/film/samoloty-planes-2013/16432
Tytuł na alltube i rok odpowiadają tym na Trakt.
(co ciekawe w tym przypadku scrapper alltube3d znajduje źródło)
log: https://hastebin.com/upugotojuq.rb
Niektóre filmy (np. "Iniemamocni") znajduje bez problemu...

**Comment by xulek** [comment]
Pojadę klasykiem :P U mnie działa, normalnie wyszukuje źródełka dla tych filmów co podałeś z alltube

**Comment by notoco** [comment]
To i ja walnę klasykiem - jaki FanFilm? Jaki system - u mnie kodi 17.6, ubuntu, ff lite ostatni ale zaraz zerknę na scrappery

**Comment by xulek** [comment]
sprawdziłem na dwóch dla pewności 2018.06.23 i 2018.06.19

**Comment by notoco** [comment]
Yhm - już mam - problem jest u mnie na kompie... na boxie działa...
