### ISSUE TITLE
FanFilm, problem z wyszukiwaniem na Kodi 18

### ISSUE THREAD

**Issue by xulek** [CherryKodi/cherry-dev#8]
Problem występuje przy funkcji Container.Update.

https://github.com/CherryKodi/cherry-dev/blob/558225fd3b4b153ee948f3e2b1be0e9af247c342/script.module.ptw/lib/resources/lib/indexers/movies.py#L220

Zauważyłem, że po wykonaniu tej wbudowanej funkcji program nie wraca już do default.py z FanFilm, a powinnien tam wrócić i wybrać:

https://github.com/CherryKodi/cherry-dev/blob/558225fd3b4b153ee948f3e2b1be0e9af247c342/plugin.video.fanfilm/default.py#L141

Próbowałem więc wywołać tą funkcję skryptem:

`xbmc.executebuiltin("ActivateWindow(10025,return)")
xbmc.executebuiltin('Container.Update("plugin://plugin.video.fanfilm/?action=moviePage&url=http://api.trakt.tv/search/Film?limit=20&page=1&query=Avatar")')`

Ale to na nic, nie odświeża kontenera :/

Prawdopodobnie jest to spowodowane script.skin.helper.service, który ma problem z opisaniem kluczy dla każdej listowanej pozycji, tak podejrzewam. Sypie on wtedy takimi błędami:

```
23:23:51.472 T:62536   ERROR: NEWADDON Unknown Video Info Key "poster"
23:23:51.472 T:62536   ERROR: NEWADDON Unknown Video Info Key "thumb"
23:23:51.472 T:62536   ERROR: NEWADDON Unknown Video Info Key "tvdb"
23:23:51.472 T:62536   ERROR: NEWADDON Unknown Video Info Key "unaired"
23:23:51.472 T:62536   ERROR: NEWADDON Unknown Video Info Key "banner"
23:23:51.472 T:62536   ERROR: NEWADDON Unknown Video Info Key "fanart"
23:23:51.472 T:62536   ERROR: NEWADDON Unknown Video Info Key "imdb"
23:23:51.472 T:62536   ERROR: NEWADDON Unknown Video Info Key "label"
23:23:51.472 T:62536   ERROR: NEWADDON Unknown Video Info Key "poster"
23:23:51.472 T:62536   ERROR: NEWADDON Unknown Video Info Key "thumb"
23:23:51.472 T:62536   ERROR: NEWADDON Unknown Video Info Key "tvdb"
23:23:51.472 T:62536   ERROR: NEWADDON Unknown Video Info Key "unaired"
23:23:51.472 T:62536   ERROR: NEWADDON Unknown Video Info Key "banner"
23:23:51.472 T:62536   ERROR: NEWADDON Unknown Video Info Key "fanart"
23:23:51.472 T:62536   ERROR: NEWADDON Unknown Video Info Key "imdb"
23:23:51.472 T:62536   ERROR: NEWADDON Unknown Video Info Key "label"
23:23:51.472 T:62536   ERROR: NEWADDON Unknown Video Info Key "poster"
```

Zaznaczę, że szukanie przez tworzenie nowego folderu i dodawanie tam nowych pozycji działa świetnie. Problem występuje tylko przy odświeżaniu kontenera funkcją xbmc.executebuiltin('Container.Update()')

**Comment by rysson** [comment]
Nie bardzo się orientuję i nie mam jak w pracy sprawdzić, ale...
Czytając wskazana przez Ciebie linki do plików nie widzę jak ma on wrócić z metody `search_new()` (w której jest wskazany `Container.Update`) do `action == 'moviePage'` skoro `search_new()` jest wołana w innych warunkach (znaczy pod innymi `ifelse`).
Masz na myśli, że cały default.py nie jest wołany jeszcze raz? Czy inne linie w kodzie?

**Comment by xulek** [comment]
tak chodziło mi o to, że default.py nie jest wywoływany kolejny raz w celu wykonania tego co znajduje się w Container.Update

**Comment by rysson** [comment]
Teraz jasne. Jeszcze się z tą funkcją nie spotkałem. Dzięki.

**Comment by xulek** [comment]
Chyba rozwiązałem problem przez obejście default.py i wykonanie bezpośrednio wyszukiwania, dziś albo jutro wrzucę poprawiony kod
